In [2]:
import numpy as np
import cv2
import cv2.aruco as aruco
parameters = aruco.DetectorParameters_create()
aruco_dict = aruco.Dictionary_get(aruco.DICT_4X4_100)
# camera_matrix =np.matrix ([[ 522.1905267183170736, 0.0000000000000000, 308.8532705794233948  ],
#                   [ 0.0000000000000000, 522.8166355728753842, 234.2130798407917496 ],
#                   [ 0.0000000000000000, 0.0000000000000000, 1.0000000000000000 ]])
# # camera_matrix = [[1000, 0, 320], [0, 1000, 240], [0, 0, 1]]  # 示例相机矩阵
# camera_dist = np.matrix([ 0.1058497356483027 ,-0.1488874492570700 ,0.0000000000000000 ,0.0000000000000000 ,-0.8698561798572152])

camera_matrix = np.matrix( [[2.87796762e+03, 0.00000000e+00, 1.00285463e+03],
                [0.00000000e+00, 3.00190524e+03, 6.19596536e+02],
                [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
camera_dist = np.matrix( [ 2.99966651e-01, -2.66624230e+00,  3.77453614e-03,  5.35117510e-03,  -2.10052144e+01])
  # marker_length: 0.012
marker_length = 0.006
parameters

< cv2.aruco.DetectorParameters 0x773d1c61f070>

In [3]:
for i in range(0, 8):
    cap = cv2.VideoCapture(i)
    if cap.isOpened():
        print( 'camera open')
        while True:
            ret, img = cap.read()
            print(ret, i)
            if not ret:
                continue
            else:
                print(ret, "camera id:")
                print(img.shape)
            #

                cv2.imshow('5', img)
                # cv2.waitKey(10)
                c = cv2.waitKey(10)
                if c == 27:
                        break
                cap.set(cv2.CAP_PROP_FPS, 330)
                # cv2.destroyAllWindows()
    cap.release()
    cv2.destroyAllWindows()
    # break

camera open
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(480, 640, 3)
True 0
True camera id:
(48

[ WARN:0@200.038] global /home/conda/feedstock_root/build_artifacts/libopencv_1671461518131/work/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video1): can't open camera by index


camera open
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(480, 640, 3)
True 2
True camera id:
(48

[ WARN:0@210.784] global /home/conda/feedstock_root/build_artifacts/libopencv_1671461518131/work/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video3): can't open camera by index
[ WARN:0@210.784] global /home/conda/feedstock_root/build_artifacts/libopencv_1671461518131/work/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video4): can't open camera by index
[ WARN:0@210.784] global /home/conda/feedstock_root/build_artifacts/libopencv_1671461518131/work/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@210.784] global /home/conda/feedstock_root/build_artifacts/libopencv_1671461518131/work/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video6): can't open camera by index
[ WARN:0@210.784] global /home/conda/feedstock_root/build_artifacts/libopencv_1671461518131/work/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video7): can't open camera by index


In [7]:
import cv2
import time
import cv2.aruco as aruco
from scipy.spatial.transform import Rotation as R

# 创建视频捕捉对象，0 表示使用默认摄像头
cap = cv2.VideoCapture(2)

# 创建 ArUco 检测参数
parameters = aruco.DetectorParameters_create()

# 加载预定义的 ArUco 字典
# aruco_dict = aruco.Dictionary_get(aruco.DICT_6X6_250)
aruco_dict = aruco.Dictionary_get(aruco.DICT_4X4_250)
i = 0
while True:
    # 读取一帧图像
    # time.sleep(1)
    ret, frame = cap.read()
    if not ret:
        break

    # 将图像转换为灰度图
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # 检测 ArUco 标记
    corners, ids, rejectedImgPoints = aruco.detectMarkers(gray, aruco_dict, parameters=parameters)
    rvecs, tvecs, _ = aruco.estimatePoseSingleMarkers(corners,
                                                          marker_length,
                                                          camera_matrix,
                                                          camera_dist)
    
    # 估计标记的姿态
    rvecs, tvecs, _ = aruco.estimatePoseSingleMarkers(corners, marker_length, camera_matrix, camera_dist)

    # 检查返回值
    if rvecs is not None and len(rvecs) > 0:
        print("Rotation Vectors:", rvecs)
        # Rotation Vectors: [[[-3.12682862  0.03934772  0.00940102]]]
        print("Translation Vectors:", tvecs)
        # Translation Vectors: [[[0.00055413 0.00014394 0.02618797]]]
        
        # 处理第一个标记的旋转向量
        rr = R.from_rotvec(rvecs[0][0])
        print("Rotation Matrix:\n", rr.as_matrix())
         # [[ 0.99966529 -0.02520588 -0.00582934]
         # [-0.02511868 -0.9995782   0.01457627]
         # [-0.00619429 -0.01442496 -0.99987677]]
    
        # 获取欧拉角（以度为单位）
        rpy = rr.as_euler('xyz', degrees=True)

    
        # 打印欧拉角
        print("Euler Angles (before adjustment):", rpy)
        # Euler Angles (before adjustment): [-179.17346597    0.35490888   -1.4393736 ]
    
        # 确保 rpy 是一个数组并且长度为 3
        if rpy.shape == (3,):
            rpy[-1] = rpy[-1] + 360 * (rpy[-1] < 0)
            rpy[0] = rpy[0] + 360 * (rpy[0] < 0)
            print("Euler Angles (after adjustment):", rpy)
            # Euler Angles (after adjustment): [1.80826534e+02 3.54908876e-01 3.58560626e+02]
            
            # 检查 tvecs[0][0] 是否有效
            if tvecs is not None and len(tvecs) > 0:
                print("Translation Vector (in mm):", tvecs[0][0] * 1000)
                # 将平移向量转换为毫米并合并
                back = np.concatenate((tvecs[0][0] * 1000, rpy))
                print("Final Vector:", back)
 #                Final Vector: [5.54131605e-01 1.43942161e-01 2.61879730e+01 1.80826534e+02
 # 3.54908876e-01 3.58560626e+02]
            else:
                print("Translation vector is None or empty.")
        else:
            print("Unexpected shape for Euler angles:", rpy.shape)
    else:
        print("未检测到任何标记或估计姿态失败")


    # 如果检测到标记，绘制边框并显示 ID
    if ids is not None:
        frame = aruco.drawDetectedMarkers(frame, corners, ids)
        # cv2.drawFrameAxes(frame, camera_matrix, camera_dist, rvecs[i], tvecs[i], 0.1)
        # print('corners:',i, corners)

    # 显示结果图像
    cv2.imshow('Aruco Detection', frame)

    # 按下 'q' 键退出
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 释放视频捕捉对象并关闭所有窗口
cap.release()
cv2.destroyAllWindows()

[ WARN:0@260.703] global /home/conda/feedstock_root/build_artifacts/libopencv_1671461518131/work/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
